# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FinanceHelper.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from fractions import Fraction


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(583, 228)
        MainWindow.setStyleSheet("background-color: rgb(170, 170, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-10, 0, 611, 291))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.spinBox = QtWidgets.QSpinBox(self.tab)
        self.spinBox.setGeometry(QtCore.QRect(10, 50, 221, 22))
        self.spinBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox.setMaximum(1000000000)
        self.spinBox.setObjectName("spinBox")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 47, 13))
        self.label_2.setObjectName("label_2")
        self.spinBox_2 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_2.setGeometry(QtCore.QRect(10, 100, 221, 22))
        self.spinBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_2.setMaximum(999999999)
        self.spinBox_2.setObjectName("spinBox_2")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(10, 130, 221, 41))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setTabletTracking(False)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
                                      "background-color: rgb(0, 170, 0);\n"
                                      "border: none;")
        self.pushButton.setCheckable(False)
        self.pushButton.setAutoRepeat(False)
        self.pushButton.setAutoExclusive(False)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(260, 70, 291, 31))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("color: rgb(85, 0, 0);\n"
                                   "font: 75 20pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_3.setGeometry(QtCore.QRect(20, 30, 201, 22))
        self.spinBox_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_3.setMaximum(999999999)
        self.spinBox_3.setObjectName("spinBox_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(20, 60, 201, 16))
        self.label_5.setObjectName("label_5")
        self.spinBox_4 = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_4.setGeometry(QtCore.QRect(20, 80, 201, 22))
        self.spinBox_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_4.setMaximum(999999999)
        self.spinBox_4.setObjectName("spinBox_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 110, 221, 41))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setTabletTracking(False)
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "background-color: rgb(0, 170, 0);\n"
                                        "border: none;")
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setAutoRepeat(False)
        self.pushButton_2.setAutoExclusive(False)
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setEnabled(True)
        self.label_6.setGeometry(QtCore.QRect(230, -20, 361, 111))
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("color: rgb(85, 0, 0);\n"
                                   "font: 75 20pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 201, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(20, 60, 201, 16))
        self.label_8.setObjectName("label_8")
        self.spinBox_5 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_5.setGeometry(QtCore.QRect(20, 80, 201, 22))
        self.spinBox_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_5.setMaximum(999999999)
        self.spinBox_5.setObjectName("spinBox_5")
        self.spinBox_6 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_6.setGeometry(QtCore.QRect(20, 30, 201, 22))
        self.spinBox_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_6.setMaximum(999999999)
        self.spinBox_6.setObjectName("spinBox_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 130, 221, 41))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setTabletTracking(False)
        self.pushButton_3.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "background-color: rgb(0, 170, 0);\n"
                                        "border: none;")
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setAutoRepeat(False)
        self.pushButton_3.setAutoExclusive(False)
        self.pushButton_3.setAutoDefault(False)
        self.pushButton_3.setDefault(False)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.spinBox_7 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_7.setGeometry(QtCore.QRect(230, 30, 201, 22))
        self.spinBox_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_7.setMaximum(999999999)
        self.spinBox_7.setObjectName("spinBox_7")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(230, 10, 201, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setEnabled(True)
        self.label_10.setGeometry(QtCore.QRect(230, 70, 500, 100))
        self.label_10.setAutoFillBackground(False)
        self.label_10.setStyleSheet("color: rgb(85, 0, 0);\n"
                                    "font: 75 20pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.start_calc()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FinanceHelper - Финансовый помощник"))
        self.label.setText(_translate("MainWindow", "Себестоимость"))
        self.label_2.setText(_translate("MainWindow", "Доход:"))
        self.pushButton.setText(_translate("MainWindow", "Расчитать"))
        self.label_3.setText(_translate("MainWindow", "Маржа: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Калькулятор маржи"))
        self.label_4.setText(_translate("MainWindow", "Объем продаж"))
        self.label_5.setText(_translate("MainWindow", "Себестоимость проданных товаров"))
        self.pushButton_2.setText(_translate("MainWindow", "Расчитать"))
        self.label_6.setText(_translate("MainWindow", "Валовая (гросс) маржа"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Валовая (гросс) маржа"))
        self.label_7.setText(_translate("MainWindow", "процентные (комиссионные) доходы"))
        self.label_8.setText(_translate("MainWindow", "процентные (комиссионные) расходы"))
        self.pushButton_3.setText(_translate("MainWindow", "Расчитать"))
        self.label_9.setText(_translate("MainWindow", "активы, приносящие доход"))
        self.label_10.setText(_translate("MainWindow", "Маржа: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Чистая процентная маржа (банковская процентная маржа) "))

    def start_calc(self):
        self.pushButton.clicked.connect(self.calc)
        self.pushButton_2.clicked.connect(self.calc_gross_margin)
        self.pushButton_3.clicked.connect(self.net_interest_margin)

    def calc(self):
        pribil = self.spinBox_2.value() - self.spinBox.value()
        self.label_3.setText("Маржа: " + str(round(pribil / self.spinBox_2.value() * 100)) + "%")

    def calc_gross_margin(self):
        gross_profit_margin = self.spinBox_3.value() - self.spinBox_4.value()

        self.label_6.setText("Валовая (гросс) маржа: " + str(round((gross_profit_margin / self.spinBox_3.value()) * 100)) + "%")


    def net_interest_margin(self):
        self.label_10.setText("Маржа: " + str((self.spinBox_6.value() / self.spinBox_5.value()) / self.spinBox_7.value()) + "%")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())